config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create,:edit,:update]
  get 'users/:id/save_user_edit' ,to: 'users#save_user_edit'

  
  resources :productions, only: [:show, :create, :destroy, :new]
  
  get 'productions/:id/transaction', to: 'productions#transaction'
  get 'productions/:id/buy', to: 'productions#buy'
  
  #gitのコミット用
  
  get 'create_productions', to: 'productions#create'
  post 'send_comment', to: 'productions#save_comment'
  post 'send_transaction_comment', to: 'productions#send_transaction_comment'
  
  resources :comments
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

  <div class="alert alert-warning">
    <ul>
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div class="alert alert-
<%= message_type %>
">
<%= message %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <!--<nav class="navbar navbar-inverse navbar-static-top">-->
  <nav class="navbar navbar-static-top navbar-custom">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ほいっと！</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          
          
          
          <% if logged_in? %>
            <li><%= link_to '出品する', new_production_path %></li>
            <li><%= link_to 'マイページ', current_user %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
  
            
          <!--<li><a href="#">新規登録</a></li>-->
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>          
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
          
          
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Hekimen-Matching</title>
    
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>
    
    <% if current_page?(root_path) %>
      <div class="row mainlogo">
        <div class="col-md-12"></div>
      </div>
    <% end %>
    
    <div class="container">
      
    <%= render 'layouts/flash_messages' %>

    <%= yield %>

    </div>
  </body>
</html>